Avoid overriding existing versioned tags.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -70,6 +70,19 @@ jobs:
       - name: Setup Docker Buildx
         uses: docker/setup-buildx-action@v1
 
+      - name: Check DockerHub image does not already exist (unless force)
+        run: |
+          if [[ "$FORCE" != "force-reuse-tag" ]]; then
+            URL="https://hub.docker.com/v2/repositories/qaware/protocurl/tags/${{ github.event.inputs.version }}"
+            JSON="$(curl -s "$URL")"
+            if [[ "$JSON" == *"\"creator\""* ]]; then
+              echo "ERROR: qaware/protocurl:${{ github.event.inputs.version }} already exists on DockerHub!"
+              echo "If you know what you are doing and this is intentional, then you may set force -> 'force-reuse-tag'."
+              exit 1
+            fi
+          fi
+          echo "OK. Building and pushing the docker image would not overwrite an existing tag."
+
       - name: DockerHub Build and Release
         uses: docker/build-push-action@v2
         with:
